### ISSUE TITLE
Files could not be expanded: service error: from /usr/lib/obs/service//kiwi_import

### ISSUE THREAD

**Issue by kargolmeister** [openSUSE/obs-service-kiwi_import#12]
Hi Christian,

I just followed your article http://openbuildservice.org/2017/05/31/studio-import/ and tried to import a kiwi package exported from SUSE Studio using a blank "openSUSE Leap 42.1, JeOS" example similar to the one you used in your exercise from may this year.
After displaying "The file 'source.kiwi.tcz' has been successfully saved." the import process stops giving "Files could not be expanded: service error: from /usr/lib/obs/service//kiwi_import:6:in `'" (see below).

Q1: Do you consider this being an obs-service-kiwi_import bug where I (as a simple stupid user) may ask you kindly to provide a correction ?
Q2: In case not: any kind of idea to overcome the reported issue by a user workaround (either in SUSE Studio or OBS) ?

Thx + Brgds,
Kargol

Error log:
service kiwi_import failed:
Use of uninitialized value $val in concatenation (.) or string at /usr/lib/obs/server/bs_admin line 1144.
/srv/obs/service/19940
/srv/obs/service/19940/src
/srv/obs/service/19940/src/_service
/srv/obs/service/19940/src/openSUSE_Leap_42.1_Server.x86_64-0.0.1.oem-kiwi_src.source.kiwi.txz
/srv/obs/service/19940/src/.old
/srv/obs/service/19940/out
/srv/obs/service/19940/var
/srv/obs/service/19940/var/cache
/srv/obs/service/19940/var/cache/obs
/srv/obs/service/19940/var/cache/obs/pfkvpB6irA92
/srv/obs/service/19940/var/cache/obs/pfkvpB6irA92/scripts
/srv/obs/service/19940/var/cache/obs/pfkvpB6irA92/scripts/inner.sh
/srv/obs/service/19940/var/cache/obs/pfkvpB6irA92/scripts/inner.sh.command
/srv/obs/service/19940/home
Running /usr/lib/obs/service//kiwi_import --outdir /var/cache/obs/pfkvpB6irA92/out
+ echo Running /usr/lib/obs/service//kiwi_import --outdir /var/cache/obs/pfkvpB6irA92/out
+ export HOME=/var/cache/obs/pfkvpB6irA92/home
+ HOME=/var/cache/obs/pfkvpB6irA92/home
+ /usr/lib/obs/service//kiwi_import --outdir /var/cache/obs/pfkvpB6irA92/out
/usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- /usr/lib/obs/service/KiwiImport/lib/kiwi_archive_finder.rb (LoadError)
from /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/lib/obs/service//kiwi_import:6:in `'

**Comment by M0ses** [comment]
@kargolmeister - Could you please recheck - this issue should be fixed now.
